# Generated by Django 2.0.2 on 2018-02-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artitcle_body',
            new_name='article_body',
        ),
    ]
